if savePlot
   % Save parameters' info to file
    fileName = strcat(path_test_result,'/parameters_',num2str(nSeg),'.txt');
    fileID = fopen(fileName,'w');
        fprintf(fileID,'%s,\n',moreInfo);
        fprintf(fileID,'\n');
        fprintf(fileID,'Machine: %s,\n',machine);
        fprintf(fileID,'Model: %s,\n',model.name);
        fprintf(fileID,'hTmax: %0.10f,\n',msh.hTmax);
        fprintf(fileID,'no. triangles: %d,\n',size(triangles,2));
        fprintf(fileID,'\n');
        fprintf(fileID,'number of days: %f,\n',maxDay);
        fprintf(fileID,'__CFL: %f,\n',CFL);
        fprintf(fileID,'\n');
        fprintf(fileID,'Use FreeFem++ mesh: %d,\n',useFFmesh);
        fprintf(fileID,'Regular mesh: %d,\n',reguMesh);
        fprintf(fileID,'\n');
        fprintf(fileID,'Use small-cut: %d,\n',pa.smallCut);
        fprintf(fileID,'\n');
        fprintf(fileID,'Newton?: %d,\n',useNewton);
        fprintf(fileID,'__itol: %f,\n',itol);
        fprintf(fileID,'\n');
        fprintf(fileID,'Use FMM: %d,\n',useFMM);
        fprintf(fileID,'__al_FMM: %f,\n',alp_FMM);
        fprintf(fileID,'__numUseFMM: %d,\n',numUseFMM);
        fprintf(fileID,'__numUseFMM: %d,\n',stepUseFMM);
        fprintf(fileID,'\n');
        fprintf(fileID,'useSUPG: %d,\n',useSUPG);
        fprintf(fileID,'__delEps: %f,\n',delEps);
        fprintf(fileID,'__delSD: %f,\n',delSD);
        fprintf(fileID,'\n');
        fprintf(fileID,'use Ghost penalty: %d,\n',pa.useGP);
        fprintf(fileID,'__gam1: %f,\n',pa.gam1);
        fprintf(fileID,'__gam2: %f,\n',pa.gam2);
        fprintf(fileID,'\n');
        fprintf(fileID,'Panalty terms:\n');
        fprintf(fileID,'__lamHu: %f,\n',cpU.lamH);
        fprintf(fileID,'__lamHv: %f,\n',cpV.lamH);
        fprintf(fileID,'\n');
        fprintf(fileID,'Model parameters:\n');
        fprintf(fileID,'__r0: %f,\n',pa.r0);
        fprintf(fileID,'____distancing: %d,\n',pa.distancing);
        fprintf(fileID,'__muS1: %f,\n',pa.muS1);
        fprintf(fileID,'__muS2: %f,\n',pa.muS2);
        fprintf(fileID,'__muP1: %f,\n',pa.muP1);
        fprintf(fileID,'__muP2: %f,\n',pa.muP2);
        fprintf(fileID,'__bcu3: %f,\n',pa.bcu3);
        fprintf(fileID,'__cpU.k1: %f,\n',cpU.kk1);
        fprintf(fileID,'__cpU.k2: %f,\n',cpU.kk2);
        fprintf(fileID,'__cpV.k1: %f,\n',cpV.kk1);
        fprintf(fileID,'__cpV.k1: %f,\n',cpV.kk1);
        fprintf(fileID,'__f: %f,\n',pa.f);
        fprintf(fileID,'__K0: %f,\n',pa.K0);
        fprintf(fileID,'__useFixedDist: %d,\n',useFixedDist);
        fprintf(fileID,'____pa.L: %f,\n',pa.L);
%     fclose(fileID); 
end